Add autoreload for libraries
GeoWerkstatt/QGIS_Map_library pull request #1
Opened 2023-05-08 09:38 UTC by olivergrimm

2023-05-08 10:30 UTC, MiraGeowerkstatt requested changes
REQ: Changelog im metadata.txt nachführen.
PP: Property im libs.json file einfügen, sodass sie bei neuem Download des Plugin bereits exitiert.

2023-05-08 10:30 UTC, MiraGeowerkstatt commented on .gitignore
> +_deploy.ps1
Q: Wofür braucht es das?

2023-05-08 10:30 UTC, MiraGeowerkstatt commented on QGIS_Map_library.code-workspace
> +}
Q: Braucht es das und wenn ja , stimmt die Formatierung so? Sieht irgendwie komisch aus :D

2023-05-08 10:30 UTC, MiraGeowerkstatt commented on readme.md
> +This feature is sponsored by [GIS of Canton of Schaffhausen, Switzerland](https://sh.ch/CMS/Webseite/Kanton-Schaffhausen/Beh-rde/Verwaltung/Volkswirtschaftsdepartement/Amt-f-r-Geoinformation-3854-DE.
Keine Ahnung ob sie das akzeptieren in einem open source repo. Wir können in der Runde nochmal besprechen, ob wir das überhaupt versuchen sollen.

2023-05-08 10:30 UTC, MiraGeowerkstatt commented on map_library.py
> +                    if not name == "LibrariesRefreshInterval":
Q: Braucht es den Check hier? Wenn ich richtig durchblicke steht der LibrariesRefreshInterval ja im libs.json und hier loopen wir durch das File das im libs.json via Pfad angegeben wird (entspricht im Beispiel dem example.json) , oder? Dann wäre dieser check höchstens dann gut, wenn jemand das ins falsche File einträgt.

2023-05-10 05:41 UTC, olivergrimm commented on readme.md
> +This feature is sponsored by [GIS of Canton of Schaffhausen, Switzerland](https://sh.ch/CMS/Webseite/Kanton-Schaffhausen/Beh-rde/Verwaltung/Volkswirtschaftsdepartement/Amt-f-r-Geoinformation-3854-DE.
Ich habs ergänzt, weil Marco - der Repo Owner - die vorherigen Erweiterungen ebenfalls so aufgeführt hat.

2023-05-10 05:46 UTC, olivergrimm commented on .gitignore
> +_deploy.ps1
Ich habe damit zwei Dateitypen (ps1 und gitignore) von der Versionierung ausgenommen. Habs nun entfernt aus dem Commit

2023-05-10 05:47 UTC, olivergrimm commented on QGIS_Map_library.code-workspace
> +}
Nein, ist die Projektdatei von VSC und gehört weg.

2023-05-10 06:55 UTC, MiraGeowerkstatt commented on readme.md
> +This feature is sponsored by [GIS of Canton of Schaffhausen, Switzerland](https://sh.ch/CMS/Webseite/Kanton-Schaffhausen/Beh-rde/Verwaltung/Volkswirtschaftsdepartement/Amt-f-r-Geoinformation-3854-DE.
Stimmt, alles klar 👍

2023-05-10 13:54 UTC, olivergrimm commented on map_library.py
> +                    if not name == "LibrariesRefreshInterval":
Nein, hier loopen wir durch das libs.json selbst. Das if habe ich eingebaut, weil der cast auf den numerischen Wert sonst einen Fehler gibt.

2023-05-12 07:25 UTC, MiraGeowerkstatt commented on .gitignore
> +_deploy.ps1
Ich glaube das ganze .gitignore file rauszuschmeissen ist keine gute Idee. Ich würde es lassen wie im main branch, einfach deine neuen Einträge rauslöschen (_deploy.ps1...), wenn es die nicht braucht.

2023-05-12 08:23 UTC, olivergrimm commented on .gitignore
> +_deploy.ps1
done

2023-05-12 08:28 UTC, merged